version: 2
jobs:
  build:
    machine: true
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      PIP_EXISTS_ACTION: w
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: pyenv local 3.5.2
    - restore_cache:
        keys:
        - v2-dep-{{ .Branch }}-
        - v2-dep-master-
        - v2-dep-
    - run: |
        python3 -m pip install -U pip setuptools wheel coverage codecov
        python3 -m pip install -U -e . -r requirements-dev.txt
    - save_cache:
        key: v2-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.cache/pip
        - ~/.local
    - run: "sudo docker info >/dev/null 2>&1 || sudo service docker start"
    - run: "py.test --cov . -ra --junitxml=$CIRCLE_TEST_REPORTS/junit.xml"
    - run: "codecov"
    - store_test_results:
        path: /tmp/circleci-test-results
